# 판다스(Pandas)
   - 데이터 분석 라이브러리
   - 행(row), 열(column) 형태의 정형 데이터 객체를 다룬다.
   
## 2차원 데이터
   - 엑셀의 시트, RDB의 테이블과 같은 형태이다.
   - 대표적인 객체 DataFrame, Series
   
## Series
   - Pandas의 기본 객체 중 하나로, numpy의 ndarray를 기반으로 인덱싱 기능이 추가된
   1차원 배열을 나타낸다. (index x value의 형태)
   - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성한다
   - index를 지정할 경우 명시적으로 지정된 index를 사용한다.
   - 같은 타입의 0개 이상의 데이터를 가질 수 있다

[판다스 공식문서](https://pandas.pydata.org/)

In [1]:
import numpy as np
import pandas as pd

In [3]:
arr1 = np.array([1, 2, 3])
print(arr1)


[1 2 3]


In [6]:
print(pd.Series(arr1, index=['a','b','c']))

a    1
b    2
c    3
dtype: int64


In [ ]:
s1

In [8]:
s2 = pd.Series([(i + 1) * 10 for i in range(5)])
s2

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
s2[0]

np.int64(10)

## ※ pd 주요 필드
- values: pd의 해당 값들을 반환하는 필드
- index: pd의 index를 반환하는 필드
- dtype: 현재 pd의 타입을 반환하는 필드

In [10]:
s2.values

array([10, 20, 30, 40, 50])

In [11]:
s2.index

RangeIndex(start=0, stop=5, step=1)

In [12]:
s2.dtype

dtype('int64')

In [13]:
names = ["홍길동", "장보고", "이순신"]
scores = [70, 80, 65]

# 값을 명시해서 넣는 것을 권장한다
pd.Series(data=scores, index=names)

홍길동    70
장보고    80
이순신    65
dtype: int64

In [17]:
incomes = {
    "한혜진": 1500000,
    "이상아": 50000,
    "오승현": 500000,
    "한우물": -10000,
    "이예나": 1000000,
    "김진휘": 1000000,
    "채진성": 1000000
}

print(incomes.keys())
print(incomes.values())

dict_keys(['한혜진', '이상아', '오승현', '한우물', '이예나', '김진휘', '채진성'])
dict_values([1500000, 50000, 500000, -10000, 1000000, 1000000, 1000000])


In [19]:
# pd.Series(incomes.values(), imcomes=incomes.keys())
s3 = pd.Series(incomes)

In [22]:
s3["오승현":"채진성"]

오승현     500000
한우물     -10000
이예나    1000000
김진휘    1000000
채진성    1000000
dtype: int64

In [23]:
incomes = {
    "한혜진": 1500000,
    "이상아": 50000,
    "오승현": 500000,
    "이예나": 1000000,
    "김진휘": 57000000,
    "채진성": 500000,
    "한우물": -10000
}

print(incomes.keys())
print(incomes.values())

dict_keys(['한혜진', '이상아', '오승현', '이예나', '김진휘', '채진성', '한우물'])
dict_values([1500000, 50000, 500000, 1000000, 57000000, 500000, -10000])


In [25]:
#한혜진의 수익을 -50000으로 변경
s3 = pd.Series(incomes)

In [28]:
s3["한혜진"] = -50000
print(s3)

한혜진      -50000
이상아       50000
오승현      500000
이예나     1000000
김진휘    57000000
채진성      500000
한우물      -10000
dtype: int64


In [33]:
print(type(s3[["이예나"]]))

<class 'pandas.Series'>


In [32]:
print(type(s3["이예나"]))

<class 'numpy.int64'>


In [34]:
# 상아, 진성
s3[['이상아','채진성']]

이상아     50000
채진성    500000
dtype: int64

In [35]:
# 원본의 view만 제공
s3[['이상아','채진성']] = 10, 10

In [36]:
s3

한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
채진성          10
한우물      -10000
dtype: int64

In [37]:
s4 = s3[['이상아','채진성']]

In [38]:
s4['이상아'] = 100
s4

이상아    100
채진성     10
dtype: int64

In [39]:
s3

한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
채진성          10
한우물      -10000
dtype: int64

In [42]:
s3.name = "수익"
s3.index.name = "이름"
s3

이름
한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
채진성          10
한우물      -10000
Name: 수익, dtype: int64

## Series 함수
    - ndim : 차원 반환
    - len : 데이터 길이
    - size : 개수 반환
    - shape : 튜플의 형태로 shape반환
    - unique : 유일한 값만 udarray로 반환
    - count : NaN을 제외한 개수를 반환
    - mean : NaN를 제외한 평균
    - value_counts : NaN를 제외하고 각 값들의 빈도를 반환

## NaN (Not a Number)
- 숫자형 데이터가 들어와야 하는데 숫자형 데이터가 아닌 다른 값이 들어왓을 때 나타나는 값
- ex) DBMS -> null, JS -> undefined, python -> None

In [45]:
s1 = pd.Series([10, 2, 3, 4, np.nan, 2, 3, 5, 7, 8, np.nan, np.nan])
s1

0     10.0
1      2.0
2      3.0
3      4.0
4      NaN
5      2.0
6      3.0
7      5.0
8      7.0
9      8.0
10     NaN
11     NaN
dtype: float64

In [46]:
s1.size

12

In [47]:
s1.shape

(12,)

In [48]:
len(s1)

12

In [50]:
s1.unique()

array([10.,  2.,  3.,  4., nan,  5.,  7.,  8.])

In [52]:
# NaN 데이터가 있다
print(s1.count())
print(len(s1))

9
12


In [53]:
s1.value_counts()

2.0     2
3.0     2
10.0    1
4.0     1
5.0     1
7.0     1
8.0     1
Name: count, dtype: int64

In [56]:
# default: 5
s1.head()
s1.head(3)

0    10.0
1     2.0
2     3.0
dtype: float64

In [58]:
# default: 5
s1.tail(3)

9     8.0
10    NaN
11    NaN
dtype: float64

## 시리즈(Series)의 연산
- 시리즈는 시리즈끼리 연산이 가능하다. 단, index를 기준으로 연산된다.
- 이 특징은 DataFrame에서도 동일하게 적용된다.

In [64]:
products = {
    "난리부르스 치킨":30000,
    "요아정 벌집 요거트": 50000,
    "그릭 요거트":13000,
    "커피": 6000,
    "떢볶이": 20000,
    "예나가 만든 샌드위치":50000
}

s2 = pd.Series(products)
s2

난리부르스 치킨       30000
요아정 벌집 요거트     50000
그릭 요거트         13000
커피              6000
떢볶이            20000
예나가 만든 샌드위치    50000
dtype: int64

In [65]:
products2 = {
    "난리부르스 치킨":30000,
    "요아정 벌집 요거트": 50000,
    "국밥": 13000,
    "라면": 6000,
    "두쫀쿠": 10000,
    "피자":30000
}


In [66]:
s3 = pd.Series(products2)
s3

난리부르스 치킨      30000
요아정 벌집 요거트    50000
국밥            13000
라면             6000
두쫀쿠           10000
피자            30000
dtype: int64

In [67]:
s2 + s3

국밥                  NaN
그릭 요거트              NaN
난리부르스 치킨        60000.0
두쫀쿠                 NaN
떢볶이                 NaN
라면                  NaN
예나가 만든 샌드위치         NaN
요아정 벌집 요거트     100000.0
커피                  NaN
피자                  NaN
dtype: float64

In [68]:
s2

난리부르스 치킨       30000
요아정 벌집 요거트     50000
그릭 요거트         13000
커피              6000
떢볶이            20000
예나가 만든 샌드위치    50000
dtype: int64

In [69]:
s2 * 1.2

난리부르스 치킨       36000.0
요아정 벌집 요거트     60000.0
그릭 요거트         15600.0
커피              7200.0
떢볶이            24000.0
예나가 만든 샌드위치    60000.0
dtype: float64

In [73]:
#가격이 3만원을 넘는 괘씸한 음식을 골라내기
price_mask = s2 > 30000
s2[price_mask]

요아정 벌집 요거트     50000
예나가 만든 샌드위치    50000
dtype: int64

In [72]:
hobbies= {
    "승현":"칵테일방, 찜질방, 노래방",
    "예나":"요리, 노래방, 영화",
    "진성":"호프,노래방, 호프집",
    "가나디":"그릭요거트, 그림그리기, 영화",
    "지혁":"음주, 흡연, 도박",
    "시우":"볼링, 클라이밍, 보석십자수"
    
}

s4 = pd.Series(hobbies)

In [74]:
#악의 축 취미를 가진 사용자를 mask로 제거하기(호프, 도박, 흡연)
print(s4)

승현       칵테일방, 찜질방, 노래방
예나          요리, 노래방, 영화
진성          호프,노래방, 호프집
가나디    그릭요거트, 그림그리기, 영화
지혁           음주, 흡연, 도박
시우      볼링, 클라이밍, 보석십자수
dtype: str


In [75]:
print(s4['지혁'])

음주, 흡연, 도박


In [87]:
evil_mask = s4.str.contains("호프|도박|흡연")
print(s4[evil_mask])


진성    호프,노래방, 호프집
지혁     음주, 흡연, 도박
dtype: str


In [95]:
evil = ['호프', '도박', '흡연']
for word in evil:
    if s4 == word:
        evil_mask = word
    

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [81]:
print(s4)

승현       칵테일방, 찜질방, 노래방
예나          요리, 노래방, 영화
진성          호프,노래방, 호프집
가나디    그릭요거트, 그림그리기, 영화
지혁           음주, 흡연, 도박
시우      볼링, 클라이밍, 보석십자수
dtype: str


In [107]:
evil_list = ['호프', '도박', '흡연']
evil_mask = [sum(evil in hobby for evil in evil_list) == 0 for hobby in s4]
evil_member = s4[evil_mask]
print(evil_member)

승현       칵테일방, 찜질방, 노래방
예나          요리, 노래방, 영화
가나디    그릭요거트, 그림그리기, 영화
시우      볼링, 클라이밍, 보석십자수
dtype: str


In [98]:
for hobby in s4:
    for evil in evil_list:
        print( evil in hobby)

False
False
False
False
False
False
True
False
False
False
False
False
False
True
True
False
False
False


In [110]:
#contains
# s4: 각행을 접근해서 글자들이 포함되어있으면 True, 아니면 False

s4[s4.str.contains("호프|도박|흡연")]

진성    호프,노래방, 호프집
지혁     음주, 흡연, 도박
dtype: str

## Series 값 삭제: drop()
- 해당 컬럼을 삭제하고 , 복제본을 반환한다.

In [114]:
s3 = pd.Series(np.arange(100, 105), index = ['a', 'b', 'c', 'd', 'e'])
s3

a    100
b    101
c    102
d    103
e    104
dtype: int64

In [115]:
s3.drop('a')

b    101
c    102
d    103
e    104
dtype: int64

In [116]:
s3

a    100
b    101
c    102
d    103
e    104
dtype: int64

In [117]:
s3.drop('a', inplace=True)

In [118]:
s3

b    101
c    102
d    103
e    104
dtype: int64

In [119]:
s3.drop(['b', 'c'])

d    103
e    104
dtype: int64

## .groupby()


In [127]:
salary_list = [
    "지혁", "희수", "승현", "우영", "희수", "시우", "슬기", "상아", "상아", "희수", "우영", "진휘", 
    "지혁", "준승", "예나", "진휘", "지호", "지혁", "희수", "승현", "시우", "준승", "우영", "예나"
]

salary_income = [
    200, 300, 400, 400, 350, 500, 300, 600, 600, 500, 600, 800,
    300, 300, 500, 500, 300, 400, 300, 800, 300, 200, 700, 500,
]

In [128]:
s1 = pd.Series(data= salary_income, index=salary_list)

s1

지혁    200
희수    300
승현    400
우영    400
희수    350
시우    500
슬기    300
상아    600
상아    600
희수    500
우영    600
진휘    800
지혁    300
준승    300
예나    500
진휘    500
지호    300
지혁    400
희수    300
승현    800
시우    300
준승    200
우영    700
예나    500
dtype: int64

In [132]:
# .count(): 개수
s1.groupby(s1.index).sum()

상아    1200
슬기     300
승현    1200
시우     800
예나    1000
우영    1700
준승     500
지혁     900
지호     300
진휘    1300
희수    1450
dtype: int64

In [133]:
s1.groupby(s1.index).mean()

상아    600.000000
슬기    300.000000
승현    600.000000
시우    400.000000
예나    500.000000
우영    566.666667
준승    250.000000
지혁    300.000000
지호    300.000000
진휘    650.000000
희수    362.500000
dtype: float64

In [134]:
s1.groupby(s1 > 300).count()

False     9
True     15
dtype: int64

In [136]:
# 600만원 이상 받은 사용자의 수
s1.groupby(s1 >= 600).count()

False    18
True      6
dtype: int64

In [142]:
s1.groupby(s1 >= 600).apply(lambda x: list(zip(x.index, x)))

False    [(지혁, 200), (희수, 300), (승현, 400), (우영, 400), (...
True     [(상아, 600), (상아, 600), (우영, 600), (진휘, 800), (...
dtype: object

In [143]:
# to~:형변환
# is~: bool
# get~:getter 값변한
# set~: setter 값 변환
print(s1.to_dict())
print(s1.to_list())

{'지혁': 400, '희수': 300, '승현': 800, '우영': 700, '시우': 300, '슬기': 300, '상아': 600, '진휘': 500, '준승': 200, '예나': 500, '지호': 300}
[200, 300, 400, 400, 350, 500, 300, 600, 600, 500, 600, 800, 300, 300, 500, 500, 300, 400, 300, 800, 300, 200, 700, 500]
